package modelo.patrimonio;
// Generated 19-sep-2011 15:52:57 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

/**
 * Cpaf0010 generated by hbm2java
 */
public class Cpaf0010 implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -2982229542587874312L;
	private int codemp;
    private String codGrp;
    private String desGrp;
    private Byte vutGrp;
    private BigDecimal fdpGrp;
    private String ctdGrp;
    private String cthGrp;
    private String codClase;
    private String acdGrp;
    private String achGrp;
    private String tipo;

    public Cpaf0010() {
    }

    public Cpaf0010(int codemp, String codGrp) {
        this.codemp = codemp;
        this.codGrp = codGrp;
    }

    public Cpaf0010(int codemp, String codGrp, String desGrp, Byte vutGrp, BigDecimal fdpGrp, String ctdGrp, String cthGrp, String codClase, String acdGrp, String achGrp, String tipo) {
        this.codemp = codemp;
        this.codGrp = codGrp;
        this.desGrp = desGrp;
        this.vutGrp = vutGrp;
        this.fdpGrp = fdpGrp;
        this.ctdGrp = ctdGrp;
        this.cthGrp = cthGrp;
        this.codClase = codClase;
        this.acdGrp = acdGrp;
        this.achGrp = achGrp;
        this.tipo = tipo;
    }

    public String getCodGrp() {
        return codGrp;
    }

    public void setCodGrp(String codGrp) {
        this.codGrp = codGrp;
    }

    public int getCodemp() {
        return codemp;
    }

    public void setCodemp(int codemp) {
        this.codemp = codemp;
    }

    public String getDesGrp() {
        return this.desGrp;
    }

    public void setDesGrp(String desGrp) {
        this.desGrp = desGrp;
    }

    public Byte getVutGrp() {
        return this.vutGrp;
    }

    public void setVutGrp(Byte vutGrp) {
        this.vutGrp = vutGrp;
    }

    public BigDecimal getFdpGrp() {
        return this.fdpGrp;
    }

    public void setFdpGrp(BigDecimal fdpGrp) {
        this.fdpGrp = fdpGrp;
    }

    public String getCtdGrp() {
        return this.ctdGrp;
    }

    public void setCtdGrp(String ctdGrp) {
        this.ctdGrp = ctdGrp;
    }

    public String getCthGrp() {
        return this.cthGrp;
    }

    public void setCthGrp(String cthGrp) {
        this.cthGrp = cthGrp;
    }

    public String getCodClase() {
        return this.codClase;
    }

    public void setCodClase(String codClase) {
        this.codClase = codClase;
    }

    public String getAcdGrp() {
        return this.acdGrp;
    }

    public void setAcdGrp(String acdGrp) {
        this.acdGrp = acdGrp;
    }

    public String getAchGrp() {
        return this.achGrp;
    }

    public void setAchGrp(String achGrp) {
        this.achGrp = achGrp;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}
